import React, { FC } from "react";
import Head from "next/head";

import Layout from "../components/Layout";
import GetFund from "../components/pages/Home/GetFund";
import Categories from "../components/pages/Home/Categories";
import Places from "../components/pages/Home/Places";
import Booking from "../components/pages/Home/Booking";
import PeopleSay from "../components/pages/Home/PeopleSay";
import WhereUs from "../components/pages/Home/WhereUs";

const Home: FC = () => {
  return (
    <Layout>
      <Head>
        <title>Pawlo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
       
          <GetFund />
        
        <Categories />
        <Places />
        <Booking />
        <PeopleSay />
        <WhereUs />
      </div>
    </Layout>
  );
};
export default Home;
